"""empty message

Revision ID: 448d9f1d3201
Revises: 
Create Date: 2019-06-06 13:04:11.495925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448d9f1d3201'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_access_control_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access', sa.Enum('deny', 'allow', name='ipaccessenum', native_enum=False), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access', 'address', name='_ipc_access_address_uc')
    )
    op.create_table('iso_country_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('block_by_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'code', name='_country_route_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    op.drop_table('routes')
    op.drop_table('iso_country_codes')
    op.drop_table('ip_access_control_list')
    # ### end Alembic commands ###
